### PR TITLE
Fix for Rethinkdb 1.16 api breaking changes as return values from create table changed ...

### PR DESCRIPTION
**Pull request by Gesias**
...from created to tables_created

### CODE REVIEW

**Comment by linkyndy** [comment]
Wow, thanks for being so fast! Will check it as fast as I can; I even hadn't had time to install the latest RethinkDB.

**Comment by Gesias** [comment]
Haha mate no need to thank me its literally one tiny micro-change, thanks for creating the orm in the first place!

**Comment by linkyndy** [comment]
Merged your PR even though wercker complained: it still seems to install an older version of RethinkDB.

Thank you for your contribution!

P.S.: Forgot to add you to the contributors list before making the release. Added you now, hope you don't mind :)

**Comment by Gesias** [comment]
Cheers bud! I hope I will have time to contribute with more significant things as I am implementing a solution based around this orm in the coming months. One thing I was thinking about was to be able to use get_or_create together with objects for foreignkey lookups as accustomed to in Django Orm for example. Thanks again for the solid effort you´ve put in!

**Comment by linkyndy** [comment]
That would sound awesome!

I have some update ideas on the pipeline, but currently not very much time for them. But in a couple of weeks I guess I'll create issues and start working on them. remodel v0.4.0 will contain some refactors as well as some new features, small ones, which would come very handy whilst using the ODM. I was indeed thinking about using related models inside queries, we'll see what I'll come up with. Meanwhile, after I open the tickets (or you can open some if you have some ideas!), we can discuss and choose the best solution. I want to keep remodel as simple as possible, without making it too _hackish_.

Until then, wish you luck with your work based on remodel and if you have any solution or need for your project, I'll be more than happy to discuss whether it would be great to be integrated in the library or not :)

**Comment by Gesias** [comment]
Sounds good! I will chew my way through the core progressively and are very open to discussions so fire away. If there are things thats easily delegated that you can drop off to me I´m more than happy to have a crack at them :)

**Pull request merged**
